export const USER_LOGIN = 'USER_LOGIN';
export const FETCHING_LOGIN = 'FETCHING_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';

export const FETCH_PASSAGELIST = 'FETCH_PASSAGELIST';
export const FETCHING_PASSAGELIST = 'FETCHING_PASSAGELIST';
export const FETCH_PASSAGELIST_ERROR = 'FETCH_PASSAGELIST_ERROR';
export const CLEAR_PASSAGELIST = 'CLEAR_PASSAGELIST';

export const FETCH_PASSAGE = 'FETCH_PASSAGE';
export const FETCHING_PASSAGE = 'FETCHING_PASSAGE';
export const FETCH_PASSAGE_ERROR = 'FETCH_PASSAGE_ERROR';
